# -*- coding: utf-8 -*-
"""irisflower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dmxnVNDcLVa4pQr2r28bhcKy9gqPbeWd

**IMPORTING LIBRARIES**
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

"""**What's in the DataSet?**"""

dataset = load_iris()
print(dataset)

print(dataset.feature_names)

print(dataset.data)

print(dataset.target)

"""**Description of data**"""

print(dataset.DESCR)

X = dataset.data
y = dataset.target

"""**DATA VISUALIZATION**"""

plt.plot(X[:, 0][y == 0] * X[:, 1][y == 0], X[:, 2][y == 0] * X[:, 3][y == 0], 'b.', label="irisSatosa")
plt.plot(X[:, 0][y == 1] * X[:, 1][y == 1], X[:, 2][y == 1] * X[:, 3][y == 1], 'r.', label="irisVirginica")
plt.plot(X[:, 0][y == 2] * X[:, 1][y == 2], X[:, 2][y == 2] * X[:, 3][y == 2], 'y.', label="irisVersicolour")
plt.legend()
plt.show()

"""**TRAINING THE MODEL**"""

X = StandardScaler().fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2)

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

"""**ACCURACY OF THE MODEL**"""

log_reg.score(X_test, y_test)

log_reg.score(X_train, y_train)

log_reg.score(X, y)